---

- name: Add prerequisite Apt packages
  become: yes
  apt:
    state: present
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add docker gpg key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: yes

- name: Add Docker ppa
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Apt packages
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
    - docker
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker-machine
  become: yes
  shell: |
    base=https://github.com/docker/machine/releases/download/v0.16.0 &&
    curl -L $base/docker-machine-{{ ansible_system | quote }}-{{ ansible_architecture | quote }} >/tmp/docker-machine &&
    sudo mv /tmp/docker-machine /usr/local/bin/docker-machine &&
    chmod +x /usr/local/bin/docker-machine
    exit 0
  args:
    creates: /usr/local/bin/docker-machine
    executable: /bin/sh

- name: Ensure "docker" group exists
  group:
    name: docker
    system: yes

- name: Ensure "{{ ansible_user_id }}" is part of the "docker" group
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker

