[user]
name = "Dylan C. Kendal"
email = "dylankendal@gmail.com"

[ui]
default-command = "log"
editor = "nvim"

[fix.tools.mix-format]
command = ["mix", "format", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.ex'", "glob:'**/*.exs'"]


[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[merge-tools.meld]
program = "meld"
edit-args = ["--newtab", "$left", "$right"]

[signing]
behavior = "keep"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPftfsUHQkoMrv8W8mDUcwOSOs7CFMitEz0qm+qOriXD"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[commit]
gpgsign = true

[revset-aliases]
'user()' = 'user("dylan.kendal@blvd.co")'
'user(x)' = 'author(x) | committer(x)'
'HEAD' = '@-'
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'nearest_nonempty(to)' = 'heads(::to & ~empty())'
'bookmark-advance-to' = 'nearest_nonempty(@)'
'stack(to)' = 'mutable() & bookmarks() & ..to'
'stack()' = 'stack(@)'

[git]
sign-on-push = true

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
'''

[aliases]
fetch = ["git", "fetch"]
push = ["git", "push"]
clone = ["git", "clone"]
n = ["new", "-r", "trunk()"]
bl = ["bookmark", "list"]
tug = ["bookmark", "advance", "--to", "nearest_nonempty(@)"]
gh = [
  "util",
  "exec",
  "--",
  "nu",
  "~/.config/jj/scripts/jj-gh.nu",
]
"bookmark-clean" = [
  "util",
  "exec",
  "--",
  "nu",
  "-c",
  """
  let bookmarks = jj bookmark list -r 'bookmarks() & ::main-' -T 'name ++ "\n"'
  if ($bookmarks | is-not-empty) {
    jj bookmark delete $bookmarks
  } else {
    print "nothing deleted"
  }
  """,
]
"gh-create" = [
  "util",
  "exec",
  "--",
  "nu",
  "~/.config/jj/scripts/jj-gh-create.nu",
]
"gh-sync" = [
  "util",
  "exec",
  "--",
  "nu",
  "~/.config/jj/scripts/jj-gh-sync.nu",
]
