[user]
name = "Dylan Kendal"
email = "dylan.kendal@blvd.co"

[ui]
default-command = "log"
editor = "nvim"

[fix.tools.mix-format]
command = ["mix", "format", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.ex'", "glob:'**/*.exs'"]


[merge-tools.hunk]
program = "nvim"
merge-args = [
    "-c :DiffEditor $left $right $output"
]

[merge-tools.meld]
program = "meld"
edit-args = ["--newtab", "$left", "$right"]

[signing]
behavior = "keep"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPftfsUHQkoMrv8W8mDUcwOSOs7CFMitEz0qm+qOriXD"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[commit]
gpgsign = true

[revset-aliases]
'user()' = 'user("dylan.kendal@blvd.co")'
'user(x)' = 'author(x) | committer(x)'
'trunk' = 'trunk()'
'HEAD' = '@-'
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[git]
sign-on-push = true

[template-aliases]
commit_description_verbose = '''
concat(
  description,
  "\n",
  "JJ: This commit contains the following changes:\n",
  indent("JJ:    ", diff.stat(72)),
  "JJ: ignore-rest\n",
  diff.git(),
)
'''

draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
'''

[aliases]
dv = ["--config=templates.draft_commit_description=commit_description_verbose", "describe"]
fetch = ["git", "fetch"]
push = ["git", "push"]
clone = ["git", "clone"]
n = ["new", "-r", "trunk()"]
bl = ["bookmark", "list"]
tug = ["bookmark", "advance"]
pr = [
  "util",
  "exec",
  "--",
  "nu",
  "-c",
  """
  let bookmark = jj log -r 'closest_bookmark(@-)' --no-graph --limit 1 --template bookmarks
  gh pr view $bookmark --web
  """,
]
