version: '3'

vars:
  nix_profile: dylankendal-mbp

tasks:
  update: nix flake update

  switch: nix run --extra-experimental-features nix-command --extra-experimental-features flakes nix-darwin -- switch --flake ./

  edit: $EDITOR ~/.config/nix-darwin/flake.nix

  clean:
    cmds:
      - sudo nix-collect-garbage --delete-older-than 30d

  lsg: sudo nix-env --list-generations --profile /nix/var/nix/profiles/system
