vim.cmd.abbr([[<expr> D@ strftime('%Y-%m-%d %a')]])
vim.cmd.abbr([[<expr> D@ strftime('%Y-%m-%d %a')]])
vim.cmd.abbr([[<expr> d@ strftime('%Y-%m-%d')]])
vim.cmd.abbr([[<expr> d@ strftime('%Y-%m-%d')]])
vim.cmd.abbr([[<expr> t@ strftime('%Y%m%d%k%M')]])
vim.cmd.abbr([[<expr> t@ strftime('%Y%m%d%k%M')]])
vim.cmd.abbr([[<expr> ts@ strftime('%Y-%m-%d %a %k:%M')]])
vim.cmd.abbr([[<expr> ts@ strftime('%Y-%m-%d %a %k:%M')]])
vim.cmd.abbr([[<expr> us@ strftime('%s')]])
vim.cmd.abbr([[<expr> us@ strftime('%s')]])
vim.cmd.abbr([[acount account]])
vim.cmd.abbr([[acount account]])
vim.cmd.abbr([[overide override]])
vim.cmd.abbr([[overide override]])
vim.cmd.abbr([[resouces resources]])
vim.cmd.abbr([[resouces resources]])
vim.cmd.abbr([[teh the]])
vim.cmd.abbr([[teh the]])

vim.cmd.cabbr([[<expr> @% expand('%')]])
vim.cmd.cabbr([[<expr> @% expand('%')]])
vim.cmd.cabbr([[<expr> @%p expand('%:p')]])
vim.cmd.cabbr([[<expr> @%p expand('%:p')]])
vim.cmd.cabbr([[<expr> R 'Rename '.expand('%:t')]])
vim.cmd.cabbr([[<expr> R 'Rename '.expand('%:t')]])
vim.cmd.cabbr([[H Helptags]])
vim.cmd.cabbr([[H Helptags]])
vim.cmd.cabbr([[V Verbose]])
vim.cmd.cabbr([[V Verbose]])
vim.cmd.cabbr([[bda Wipeout]])
vim.cmd.cabbr([[bda Wipeout]])

vim.cmd.iabbr([[abbr abbreviation]])
vim.cmd.iabbr([[abbr abbreviation]])
vim.cmd.iabbr([[abbrs abbreviations]])
vim.cmd.iabbr([[abbrs abbreviations]])
vim.cmd.iabbr([[descr description]])
vim.cmd.iabbr([[descr description]])
vim.cmd.iabbr([[dnt don't]])
vim.cmd.iabbr([[dnt don't]])
vim.cmd.iabbr([[docu document]])
vim.cmd.iabbr([[docu document]])
vim.cmd.iabbr([[dont don't]])
vim.cmd.iabbr([[dont don't]])
