---
- name: Install dev tools
  become: yes
  apt:
    name:
    - jq
    - fonts-roboto
    - tig
    - moreutils
    - avahi-daemon
    - xdotool
    - mlocate
    - pv
    - entr
    - rename
    - postgresql
    - shellcheck
    - flatpak
    - gnuplot
    - inotify-tools

- name: Install ripgrep
  become: yes
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep_12.0.1_amd64.deb

- name: Install Bat
  become: yes
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.13.0/bat-musl_0.13.0_amd64.deb

- name: Install Deno
  shell: |
    curl -fsSL https://deno.land/x/install/install.sh | sh
  args:
    executable: /bin/sh

- name: Install Kitty
  shell: |
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: "{{ ansible_user_dir }}/.local/kitty.app"
    executable: /bin/sh

- name: Link Kitty
  become: yes
  shell: |
    ln -s {{ ansible_user_dir }}/.local/kitty.app/bin/kitty /usr/local/bin/
  args:
    creates: /usr/local/bin/kitty
    executable: /bin/sh

- name: Set x-terminal-emulator
  become: yes
  alternatives:
    name: x-terminal-emulator
    path: /usr/local/bin/kitty

- name: Setup python for neovim
  shell:
    cmd: |
      python2 -m pip install --user --upgrade pynvim &&
      python3 -m pip install --user --upgrade pynvim
